website: http://marcely.de
version: 1.3
name: Essentials_KitGUI
author: Marcely1199
main: de.marcely.kitgui.main
description: A GUI for the command /kit
softdepend: [Essentials,EssentialsX]
commands:
    kit: 
      description: Essentials /kit with gui
      usage: /kit
    kitcfg: 
      description: Configurations for /kit GUI
      usage: /kitcfg